---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'eslint:recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  no-undef: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  consistent-return: 2
  no-else-return: 1
  semi: [1, 'always']
  space-unary-ops: 2
